# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.City'),
        ),
    ]
