# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=15)),
                ('sellers', models.SmallIntegerField()),
                ('storage', models.SmallIntegerField()),
                ('city', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('site', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='type_of_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.TypeOfStore'),
        ),
    ]
