# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_auto_20180811_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='store',
            name='sellers',
        ),
        migrations.AddField(
            model_name='store',
            name='sellers',
            field=models.ManyToManyField(related_name='seller_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
